apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: devops-showcase
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: ConfigMap
      name: devops-showcase-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
      - op: replace
        path: /data/LOG_LEVEL
        value: info

images:
  - name: ghcr.io/OWNER/devops-showcase
    newTag: latest
